version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_local
    environment:
      POSTGRES_USER: user1      # Set your PostgreSQL username
      POSTGRES_PASSWORD: pass1  # Set your PostgreSQL password
      POSTGRES_DB: postgresdb       # Set your database name
    ports:
      - "5432:5432"  # Expose port 5432 for local access
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data locally
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
